export class questionPool{

    // map: timePeriod -> (questionId -> questionText)
    // time periods are:
        // 0: N/A
        // 1: 1200-1300
        // 2: 1400-1500
        // 3: 1500-1650
        // 4: 1750-1900
        // 5: 1900-1945
        // 6: 1945-2026
    private questions: Record<number, Record<number, string>> = {
        0: {
            // N/A
            0: "How do you see this?",
            1: "You shouldn't be here",
            2: "Your end is nigh."
        },
        1: {
            0: "How did the Medieval Warm Period impact agricultural expansion and interactions with the environment in Northern Europe?",
            1: "In what ways did the Mongol Empire alter the social and political landscape of Asia and Eastern Europe?",
            2: "How did the introduction of the heavy plow change the economic output of manorial estates?",
            3: "What was the cultural significance of the rise of Gothic architecture in 13th-century France?",
            4: "How did the social structure of the Crusader States function upon their establishment in the Levant?",
            5: "What technological advancements in ribbed vaulting allowed for the construction of larger cathedrals?",
            6: "How did the onset of the Little Ice Age affect the Norse settlements and their environment in Greenland?",
            7: "What economic consequences arose from the establishment and expansion of the Hanseatic League?",
            8: "How did the bubonic plague's early outbreaks along Silk Road trade routes impact social cohesion?",
            9: "What role did the Magna Carta play in shaping the political limits of the English monarchy?",
            10: "How did Scholasticism influence the cultural and intellectual life of newly founded European universities?",
            11: "In what ways did the magnetic compass improve maritime navigation and economic trade for European merchants?",
            12: "How did the widespread deforestation of Europe alter the interaction between humans and their local environments?",
            13: "What social mobility was possible for women in the burgeoning urban centers of the 13th century?",
            14: "How did the reign of Kublai Khan centralize political authority in Yuan China?",
            15: "What economic factors drove the Italian city-states to dominate Mediterranean trade routes?",
            16: "How did troubadour culture reflect the shifting social values and chivalric codes of the aristocracy?",
            17: "How did the proliferation of watermills affect the technological productivity of rural communities?",
            18: "How did the failed Crusades impact the political stability and cultural prestige of the Byzantine Empire?",
            19: "What role did the Silk Road play in the cultural exchange of ideas, technologies, and religions between East and West?",
            20: "How did the feudal system dictate the economic responsibilities of serfs to their local lords?",
            21: "What were the environmental impacts of standardized farming techniques like the three-field system?",
            22: "How did the Albigensian Crusade alter the political and cultural landscape of Southern France?",
            23: "What social pressures led to the creation of the mendicant orders like the Franciscans and Dominicans?",
            24: "How did the widespread use of windmills transform the economic viability of the Low Countries?",
            25: "In what ways did the Inquisition serve as a political tool for maintaining cultural and religious conformity?",
            26: "How did the codification of common law impact the social rights of English barons and nobles?",
            27: "What economic stimuli did the Mongol Pax Mongolica provide to Eurasian trade networks?",
            28: "How did the construction of concentric castles reflect the technological state of siege warfare?",
            29: "What impact did the translation of Arabic texts have on the cultural rebirth of European scholarship?",
            30: "How did seasonal famines shape the demographic interactions with the environment in the 1200s?",
            31: "What defined the political relationship and power struggles between the Papacy and the Holy Roman Empire?",
            32: "How did the rise of craft guilds influence the social and economic life of medieval towns?",
            33: "What cultural exchanges occurred during the Mongol invasions of the Islamic world?",
            34: "How did the advancement of the spinning wheel alter the textile economy of the era?",
            35: "How did the draining of swamps for agriculture change the environmental landscape of Northern Europe?",
            36: "What was the political impact of the Battle of Bouvines on the balance of power in Western Europe?",
            37: "How did Jewish communities navigate the social and economic restrictions imposed upon them?",
            38: "In what ways did the emergence of vernacular literature shift cultural expression away from Latin?",
            39: "What role did early gunpowder, introduced from China, play in the technological shifts of 13th-century warfare?",
            40: "How did overgrazing affect the environmental sustainability of Mongol pastoralism?",
            41: "What economic policies allowed the Mali Empire to control and expand the trans-Saharan gold trade?",
            42: "How did the Mongol destruction of Baghdad impact the cultural heritage of the Islamic Golden Age?",
            43: "What political strategies did the Kamakura Shogunate use to defend Japan against the Mongol invasions?",
            44: "How did the social class of the buke (samurai) shape the cultural ethos of feudal Japan?",
            45: "What technological innovations in shipbuilding, like the cog, facilitated the trade routes of the Baltic Sea?",
            46: "How did the mining of silver affect the economic and environmental conditions in Central Europe?",
            47: "What was the cultural significance of Thomas Aquinas's synthesis of Aristotelian logic and Christian theology?",
            48: "How did the political fragmentation of the Italian peninsula foster the rise of condottieri?",
            49: "In what ways did the environmental shifts of the 13th century contribute to the eventual decline of the Anasazi?"
        },
        2: {
            0: "How did the Little Ice Age affect the agricultural and economic stability of Northern Europe?",
            1: "What political factors led to the Fall of Constantinople and the end of the Byzantine Empire?",
            2: "How did the cultural movement of the Renaissance redefine the social role of the artist?",
            3: "What economic impacts did the establishment of the first printing press have on European society?",
            4: "How did early Portuguese caravels alter the technological capabilities of maritime exploration?",
            5: "In what ways did the interaction with the Azores and Madeira influence Portuguese environmental management?",
            6: "How did the political philosophy of civic humanism shift the cultural perspectives on governance in city-states?",
            7: "What role did the Hanseatic League play in the economic dominance of the Baltic Sea region?",
            8: "How did the social upheavals of the Jacquerie and English Peasants' Revolt reflect class tensions?",
            9: "What technological advances in metallurgy allowed for the production of blast furnaces in Europe?",
            10: "How did the Ming Dynasty's political isolationism affect its economic and environmental policies?",
            11: "What cultural exchanges occurred along the Swahili Coast between African and Asian maritime traders?",
            12: "How did the introduction of sugarcane plantations on Atlantic islands alter the economic and social landscape?",
            13: "In what ways did the Ottoman-Venetian wars reshape the political boundaries and trade interactions of the Mediterranean?",
            14: "How did the printing press democratize cultural and intellectual access across Western Europe?",
            15: "What environmental consequences resulted from the expansion of sheep farming for the English wool trade?",
            16: "How did the War of the Roses impact the political centralization and social order of England?",
            17: "What economic crises were triggered by the demographic shifts following the Black Death?",
            18: "How did the social structures of the Songhai Empire facilitate its dominance in West Africa?",
            19: "What technological innovations in architecture distinguished the early Renaissance from the Gothic period?",
            20: "How did the unification of Spain under Ferdinand and Isabella alter the political landscape of the Iberian Peninsula?",
            21: "What was the cultural impact of the Medici family's patronage on the artistic environment of Florence?",
            22: "How did the environmental degradation of Easter Island affect the social collapse of its inhabitants?",
            23: "What economic mechanisms and joint ventures financed the early voyages of Christopher Columbus?",
            24: "How did the encomienda system shape the social hierarchy in the early Spanish colonies?",
            25: "In what ways did the mechanical clock transform the economic and social organization of urban life?",
            26: "How did the Reconquista drive the cultural and political integration of Spain?",
            27: "What role did the Inca road system play in the political and economic integration of the Andes?",
            28: "How did the introduction of the matchlock arquebus change the technological nature of infantry warfare?",
            29: "What environmental factors contributed to the failure of the Viking colony in Greenland during this period?",
            30: "How did the political structure of the Aztec Triple Alliance function in Mesoamerica?",
            31: "What cultural significance did the invention of moveable type have for the spread of knowledge?",
            32: "How did the rise of early capitalism in Italian city-states affect social inequality?",
            33: "What economic role did gold play in the expansion of the Mali and Songhai empires?",
            34: "How did the adaptation to mountainous terrain shape the interaction between the Swiss Confederacy and the Habsburgs?",
            35: "What technological advancements in navigation, such as the astrolabe, improved open-ocean travel?",
            36: "How did the political doctrine of the Divine Right of Kings begin to manifest in late 15th-century Europe?",
            37: "In what ways did the forced conversion and expulsion of Spanish Jews alter the cultural and economic fabric of Spain?",
            38: "How did the expansion of arable land through land reclamation impact the environment of the Netherlands?",
            39: "What social pressures led to the emergence of the burgher middle class in medieval towns?",
            40: "How did the cultural flourishing of the Timurid Renaissance manifest in Samarkand?",
            41: "What political maneuverings allowed Moscow to emerge as the dominant power in Rus'?",
            42: "How did the establishment of the triangular trade begin to shape the economic relations between Europe, Africa, and the Americas?",
            43: "What environmental impact did the introduction of European livestock have on the Caribbean ecosystem?",
            44: "How did the rise of mercenary armies change the social and political dynamics of the Italian Wars?",
            45: "In what ways did the use of linear perspective revolutionize the cultural representation of space in art?",
            46: "What economic effects did the silver influx from Central European mines have on late 15th-century currency?",
            47: "How did the cultural practice of compulsory labor (mita) function within the Inca Empire?",
            48: "What technological advancements in shipbuilding, such as the carrack, enabled intercontinental voyages?",
            49: "How did the Treaty of Tordesillas attempt to resolve the political and economic disputes between Spain and Portugal?"
        },
        3: {
            0: "How did the Columbian Exchange alter the environmental and agricultural landscapes of both hemispheres?",
            1: "What were the political consequences of the Protestant Reformation on the Holy Roman Empire?",
            2: "How did the economic theory of mercantilism drive European colonial expansion?",
            3: "What cultural shifts resulted from the spread of humanist ideas during the Northern Renaissance?",
            4: "In what ways did the introduction of the wheel-lock musket alter the technology of infantry warfare?",
            5: "How did the social fabric of indigenous American societies change following European contact and conquest?",
            6: "What environmental impact did the widespread deforestation of the Americas have on global climate patterns?",
            7: "How did the political centralization under Louis XIII and Cardinal Richelieu shape the French state?",
            8: "What economic role did the VOC (Dutch East India Company) play in the globalization of trade?",
            9: "How did the cultural patrons of the High Renaissance, like the Papacy, influence artistic expression?",
            10: "What technological innovations in cartography improved the accuracy of global navigation?",
            11: "How did the social condition of the peasantry deteriorate during the German Peasants' War?",
            12: "In what ways did the Scientific Revolution challenge the cultural and intellectual authority of the Catholic Church?",
            13: "How did the ecological transfer of silver from the Americas to Asia impact global economies?",
            14: "What political dynamics defined the Elizabethan era and England's naval conflicts with Spain?",
            15: "How did the transatlantic slave trade establish new social hierarchies in the Americas?",
            16: "What technological improvements in Dutch windmills allowed for the draining of polders and economic expansion?",
            17: "How did the Council of Trent address both the political and cultural challenges of the Counter-Reformation?",
            18: "What economic consequences did the Price Revolution have on the Spanish domestic economy?",
            19: "How did the environmental exploitation of Brazilian wood (Pau-Brasil) shape early Portuguese colonial interactions?",
            20: "In what ways did the Tokugawa Shogunate enforce political isolationism and social control in Japan?",
            21: "How did the early Enlightenment thought begin to challenge traditional political paradigms?",
            22: "What technological advancements in deep mining allowed for the extraction of silver veins in Potosí?",
            23: "How did the economic shift toward cash crops like tobacco alter the social structure of the Chesapeake colonies?",
            24: "What political factors led to the Eighty Years' War and Dutch independence from Spain?",
            25: "How did the introduction of European diseases interact with the demographic collapse of indigenous populations?",
            26: "In what ways did the cultural exchange along the Manila Galleons link the economies of Asia and the Americas?",
            27: "How did the political philosophy of absolutism manifest in the reign of Philip II of Spain?",
            28: "What role did joint-stock companies play in the economic and technological advancement of long-distance trade?",
            29: "How did the social status of women evolve in the context of the European witch hunts?",
            30: "What environmental consequences resulted from the introduction of wheat and sugar to the Americas?",
            31: "How did the cultural and political dynamics of the Ottoman Empire shift under Suleiman the Magnificent?",
            32: "What economic mechanisms funded the construction of the Taj Mahal and Mughal architectural achievements?",
            33: "How did the invention of the spinning wheel alter social and economic textile production in Asia and Europe?",
            34: "In what ways did the interaction between European settlers and Native Americans reshape the political borders of North America?",
            35: "What technological and environmental factors contributed to the Little Ice Age's impact on European agriculture?",
            36: "How did the political upheavals of the English Civil War influence the cultural discourse on governance?",
            37: "What economic impact did the influx of New World gold have on the Ming Dynasty's monetary system?",
            38: "How did the societal structure of the Mughal Empire accommodate diverse cultural and religious groups?",
            39: "What advancements in astronomical technology allowed Kepler and Galileo to challenge geocentric models?",
            40: "How did the introduction of the potato to Europe alter the environmental and social capacity for population growth?",
            41: "In what ways did the establishment of the French Academy shape the cultural production of the 17th century?",
            42: "What political strategies did Oda Nobunaga use to begin the unification of Japan?",
            43: "How did the economic shift toward maritime trade routes affect the overland Silk Road's social and economic vitality?",
            44: "What cultural significance did the Khipu serve in the political and economic administration of the Inca?",
            45: "How did the advancement of artillery render medieval castle architecture technologically obsolete?",
            46: "How did the environmental degradation of Caribbean islands result from early colonial cash crop agriculture?",
            47: "What social and political implications arose from the spread of Calvinism throughout Europe?",
            48: "How did the economic rivalry between the Dutch and Portuguese shape the political map of Southeast Asia?",
            49: "In what ways did the invention of the microscope open new cultural and scientific perspectives on the natural world?"
        },
        4: {
            0: "How did the harnessing of coal power alter the environmental and economic landscapes of Britain?",
            1: "What political ideals of the Enlightenment catalyzed the American and French Revolutions?",
            2: "How did the social structure of the ancien régime contribute to the outbreak of the French Revolution?",
            3: "What economic consequences arose from the transition from mercantilism to free-market capitalism?",
            4: "In what ways did the invention of the steam engine revolutionize industrial and transportation technology?",
            5: "How did the agricultural revolution impact the environment and population capacity of Europe?",
            6: "What political and social ramifications resulted from the Haitian Revolution?",
            7: "How did the cultural movement of Romanticism respond to the industrialization of the natural world?",
            8: "What economic role did cotton play in the expansion of the transatlantic slave trade and textile mills?",
            9: "How did the telegraph transform the technological infrastructure of global communication?",
            10: "In what ways did the rapid urbanization of the Industrial Revolution alter social living conditions?",
            11: "How did the political ideologies of nationalism reshape the map of Europe during the 19th century?",
            12: "What economic impacts did the Opium Wars have on the Qing Dynasty's interaction with the West?",
            13: "How did the cultural assimilation policies of colonial powers affect indigenous societies in Australia and North America?",
            14: "What technological advancements in steel production, like the Bessemer process, drive the Second Industrial Revolution?",
            15: "How did the exploitation of rubber in the Congo Free State demonstrate the environmental and social horrors of imperialism?",
            16: "What political strategies did Simon Bolivar employ to achieve independence for Latin American nations?",
            17: "How did the social contract theory influence the drafting of new constitutions in the late 18th century?",
            18: "What economic factors led to the creation of the factory system and the division of labor?",
            19: "In what ways did the cultural shift toward realism in literature and art reflect the social struggles of the working class?",
            20: "How did the introduction of railroads impact the economic and environmental geography of the United States?",
            21: "What political tensions regarding states' rights and slavery led to the American Civil War?",
            22: "How did the Meiji Restoration alter the social, political, and technological landscape of Japan?",
            23: "What economic motivations drove the Scramble for Africa among European powers?",
            24: "How did the cultural philosophy of Social Darwinism justify the political domination of imperial territories?",
            25: "In what ways did the invention of the telephone reshape social interactions and business economics?",
            26: "How did the proliferation of cash crop plantations in Southeast Asia impact the local environments and native social structures?",
            27: "What political role did the Congress of Vienna play in restoring the balance of power in Europe?",
            28: "How did the theory of evolution introduce a cultural paradigm shift regarding humanity's place in the natural environment?",
            29: "What economic disparities fueled the growth of socialist and labor movements in the 19th century?",
            30: "How did the internal combustion engine represent a major technological leap for transportation?",
            31: "In what ways did the political doctrine of the Monroe Doctrine shape the interactions of the United States with Latin America?",
            32: "How did the discovery and application of vaccines alter the social and demographic history of infectious diseases?",
            33: "What economic impact did the California Gold Rush have on the global migration of labor?",
            34: "How did the cultural movement of abolitionism shape the political discourse in the British Empire?",
            35: "What technological innovations in sanitation improved the urban environment and public health?",
            36: "How did the unification of Germany under Bismarck shift the political balance of European power?",
            37: "In what ways did the expansion of the railway systems in India serve both the economic interests of Britain and the social integration of the subcontinent?",
            38: "How did the economic crisis of the Long Depression in the late 19th century affect global trade policies?",
            39: "What cultural transformations occurred in the Ottoman Empire during the Tanzimat reforms?",
            40: "How did the invention of photography technologically and culturally change the documentation of history?",
            41: "How did the massive deforestation of the American Midwest alter the environmental interactions of the frontier?",
            42: "What social and economic roles did women adopt during the Industrial Revolution?",
            43: "How did the political structure of the Zulu Empire enable its resistance against British imperialism?",
            44: "In what ways did the opening of the Suez Canal reshape global economic and maritime interactions?",
            45: "What cultural impact did the World's Fairs have on the public perception of technological progress?",
            46: "How did the Dreyfus Affair reveal the social and political undercurrents of anti-Semitism in France?",
            47: "What economic and environmental effects did the guano trade have on the Pacific Islands?",
            48: "How did the development of early electric grids and lighting transform the social organization of urban nightlife?",
            49: "In what ways did the Russo-Japanese War alter the geopolitical and technological perceptions of European supremacy?"
        },
        5: {
            0: "How did the mechanized warfare of WWI alter the physical environment and landscape of Western Europe?",
            1: "What political factors led to the collapse of the Romanov Dynasty and the rise of the Soviet Union?",
            2: "How did the economic instability of the Weimar Republic contribute to the social rise of fascism?",
            3: "In what ways did the cultural explosion of the Roaring Twenties challenge traditional social norms?",
            4: "How did the development of tanks and aircraft change the technological nature of combat?",
            5: "What economic consequences did the Treaty of Versailles have on the global post-war order?",
            6: "How did the environmental disaster of the Dust Bowl affect the social and economic migration within the United States?",
            7: "What political strategies characterized the New Deal in response to the Great Depression?",
            8: "How did the cultural movement of Surrealism reflect the psychological impacts of global conflict?",
            9: "What technological leaps in radio broadcasting transform political communication and social entertainment?",
            10: "In what ways did the political ideology of Nazism manipulate social fears and economic anxieties?",
            11: "How did the social conditions of colonial subjects in Asia and Africa shift during WWI?",
            12: "What economic factors drove the rapid industrialization of the Soviet Union under Stalin?",
            13: "How did the invention of penicillin revolutionize the medical and social approach to bacterial infections?",
            14: "What political compromises were made at the Munich Conference, and how did they impact the diplomatic environment of appeasement?",
            15: "How did the cultural and social narrative of the Lost Generation express the disillusionment of the post-WWI era?",
            16: "In what ways did the development of radar provide a technological advantage during the Battle of Britain?",
            17: "How did the economic devastation of the Great Depression alter global trade and interaction networks?",
            18: "What political and social impact did the suffragette movement have on the democratization of Western nations?",
            19: "How did the mechanized assembly line of Henry Ford revolutionize both economic production and social consumerism?",
            20: "In what ways did the environmental exploitation of resources in Manchuria fuel Japanese imperial expansion?",
            21: "How did the political ideology of Pan-Arabism begin to shape the social landscape of the Middle East?",
            22: "What economic policies of FDR's New Deal redefined the social contract between the state and its citizens?",
            23: "How did the cultural and intellectual migration of European scholars to America impact the scientific community?",
            24: "What technological advancements in cryptography, such as the Enigma machine, influence the outcome of WWII?",
            25: "How did the interaction between labor and management during the interwar period lead to the rise of powerful unions?",
            26: "What political dynamics resulted from the partitioning of the Ottoman Empire's territories?",
            27: "In what ways did the social realism of Soviet art serve the political objectives of the state?",
            28: "How did the economic hyperinflation of the 1920s destroy the social savings of the German middle class?",
            29: "What environmental transformations occurred due to the massive public works projects of the TVA?",
            30: "How did the development of the atomic bomb fundamentally change the technological and political realities of warfare?",
            31: "In what ways did the political trajectory of Chiang Kai-shek and the KMT shape the social dynamics of China?",
            32: "How did the Harlem Renaissance culturally redefine the social identity of African Americans?",
            33: "What economic theories of Keynesianism were applied to combat the social devastation of the Depression?",
            34: "How did the interaction of global markets during the 1929 stock market crash expose economic vulnerabilities?",
            35: "What technological innovations in aviation, like the Hindenburg, capture the public's cultural imagination before its destruction?",
            36: "How did the political failures of the League of Nations impact the global response to early acts of aggression?",
            37: "In what ways did the Spanish Civil War serve as a political and technological testing ground for WWII?",
            38: "How did the social welfare policies of the Nordic countries establish an economic middle ground during this era?",
            39: "What cultural impact did the invention of the television have on the dissemination of political propaganda?",
            40: "How did the environmental and resource demands of total war mobilize entire societies and economies?",
            41: "What political and economic forces drove the federal internment of Japanese Americans during WWII?",
            42: "In what ways did the Marshall Plan seek to reconstruct the economic and social infrastructure of Europe?",
            43: "How did the evolution of jazz reflect the cultural and social syncretism of the early 20th century?",
            44: "What technological and economic strategies allowed the United States to become the Arsenal of Democracy?",
            45: "How did the social disruption of the Mexican Revolution alter the political and environmental landscape of Mexico?",
            46: "In what ways did the political doctrine of Self-Determination begin to reshape the colonial environment?",
            47: "What economic impact did the shift to a wartime economy have on the social roles of women in the workforce?",
            48: "How did the cultural phenomenon of cinema serve as both an escape from and a reflection of the Great Depression?",
            49: "What technological characteristics of the V2 rocket paved the way for the post-war Space Race?"
        },
        6: {
            0: "How did the geopolitical doctrine of Containment shape the political and military interactions of the Cold War?",
            1: "What economic factors led to the rapid decolonization of Africa and Asia following WWII?",
            2: "In what ways did the cultural movements of the 1960s challenge the established social and political order?",
            3: "How did the development of the internet revolutionize global technological, economic, and social interactions?",
            4: "What environmental consequences resulted from the widespread use of pesticides like DDT?",
            5: "How did the political tensions of the Cuban Missile Crisis bring the world to the brink of nuclear war?",
            6: "What economic disparities between the Global North and South were exacerbated by neoliberal globalization?",
            7: "In what ways did the Civil Rights Movement alter the social and political fabric of the United States?",
            8: "How did the cultural export of American consumerism impact the social values of post-war Europe and Japan?",
            9: "What technological advancements in satellite communications transform global media and political discourse?",
            10: "How did the ecological disasters of the late 20th century, like Chernobyl, shape the environmental and political policies of the Soviet bloc?",
            11: "What economic strategies fueled the rise of the Asian Tigers, and how did they alter global trade interactions?",
            12: "In what ways did the political collapse of the USSR redefine the geopolitical environment of Eastern Europe?",
            13: "How did the social and political advocacy of Second-Wave Feminism transform economic opportunities for women?",
            14: "What cultural shifts were driven by the global proliferation of rock and roll and hip-hop music?",
            15: "How did the microprocessor and personal computer transform the technological and economic capabilities of individuals?",
            16: "What environmental discussions emerged from the Kyoto Protocol regarding climate change and global interactions?",
            17: "How did the political realities of the Apartheid regime in South Africa affect its international economic and social standing?",
            18: "In what ways did the economic reforms of Deng Xiaoping integrate China into the global capitalist environment?",
            19: "How did the social panic of the HIV/AIDS epidemic influence cultural responses and medical technological funding?",
            20: "What political dynamics of the Non-Aligned Movement sought to navigate the Cold War environment?",
            21: "How did the invention of the smartphone alter the social, economic, and cultural interactions of the 21st century?",
            22: "In what ways did the economic bubbles of the Dot-Com era and 2008 Financial Crisis shape modern regulatory politics?",
            23: "How did the cultural and political map of the Middle East shift following the Iranian Revolution?",
            24: "How did the technological innovations in renewable energy aim to mitigate the environmental impacts of fossil fuels?",
            25: "How did the political doctrine of the War on Terror reconfigure global alliances and social liberties?",
            26: "In what ways did the economic integration of the European Union affect the political sovereignty of its member states?",
            27: "How did the environmental movement of the 1970s culturally and politically redefine the relationship between society and nature?",
            28: "What social transformations occurred in Latin America during the Pink Tide political shifts?",
            29: "How did the technological race to sequence the human genome open new cultural and economic frontiers in medicine?",
            30: "How did the political reforms of Gorbachev, Glasnost and Perestroika, alter the social and economic realities of the Soviet Union?",
            31: "In what ways did the rapid urbanization of the developing world create new environmental and social challenges?",
            32: "How did the economic principle of supply-side economics influence the political landscape of the 1980s?",
            33: "What cultural and social impact did the introduction of the birth control pill have on the modern family structure?",
            34: "How did technological advancements in drone warfare change the political and ethical environments of modern conflict?",
            35: "In what ways did the interaction between global fishing industries and marine ecosystems lead to environmental collapse?",
            36: "How did the political and economic rise of BRICS nations challenge Western global hegemony?",
            37: "What social and cultural shifts resulted from the legalization of same-sex marriage in various nations?",
            38: "How did the development of mRNA vaccine technology alter the global response to the COVID-19 pandemic?",
            39: "What economic and environmental factors drove the Arctic sovereignty disputes among northern nations?",
            40: "How did the political leadership of Nelson Mandela guide the social transition from Apartheid to democracy in South Africa?",
            41: "In what ways did the advent of social media platforms disrupt traditional economic and political communications?",
            42: "How did the cultural globalization of fast food impact the dietary health and social environments of developing nations?",
            43: "What economic policies of the IMF and World Bank affected the social infrastructure of developing nations?",
            44: "How did the technological advancements in fracking alter the global energy environment and political landscape?",
            45: "In what ways did the Arab Spring utilize social technology to demand political and social change?",
            46: "How did the political conflict in Rwanda shape the international community's approach to humanitarian intervention?",
            47: "What cultural and economic significance does the rise of K-Pop have on South Korea's global soft power?",
            48: "How did the environmental devastation of the Amazon rainforest ignite global political and social activism?",
            49: "In what ways has artificial intelligence begun to transform the economic, social, and technological foundations of the modern world?"
        }

    };

    constructor(initial?: Record<number, Record<number, string>>){
        if (initial) this.questions = initial;
    }

    public getTimePeriods(): number[] {
        return Object.keys(this.questions).map(Number);
    }

    public getQuestion(timePeriod: number, questionId: number): string {
        const period = this.questions[timePeriod];
        if (!period) return "";
        return period[questionId] ?? "";
    }

    public getQuestionIds(timePeriod: number): number[] {
        const period = this.questions[timePeriod];
        if (!period) return [];
        return Object.keys(period).map(Number);
    }

    public setQuestion(timePeriod: number, questionId: number, text: string): void {
        if (!this.questions[timePeriod]) this.questions[timePeriod] = {};
        this.questions[timePeriod][questionId] = text;
    }

    public deleteQuestion(timePeriod: number, questionId: number): boolean {
        const period = this.questions[timePeriod];
        if (!period || !(questionId in period)) return false;
        delete period[questionId];
        if (Object.keys(period).length === 0) delete this.questions[timePeriod];
        return true;
    }
}